### ISSUE TITLE
Portal to Alfheim part 2 auto completes early on (and other ghost quests)

### ISSUE THREAD

**Issue by armuell** [8bit-Build/Peace-of-Mind#1]
I don't even know if this quest exists anymore but it completed when I acquired some mundane items during early game through crafting. Better questing has a habit/bug related to using the editor where these ghost quests get created/not deleted correctly, occasionally they will complete themselves depending on what their requirements are.

**Comment by chunkedelement** [comment]
Ok thanks for feedback, will check for release version 2.1.0

**Comment by chunkedelement** [comment]
Fixed, found ghost quest, should be sorted 2.1.0

**Comment by chunkedelement** [comment]
2.1.0

**Comment by chunkedelement** [comment]
This is still active apparently again even though tested. Will check again as there must be two of these ghost quests. Doesn't effect main questbook completion. Will verify for 2.1.2

**Comment by chunkedelement** [comment]
Should be addressed checked and removed ghost quests 2.1.2

**Comment by chunkedelement** [comment]
Closing for now
