### ISSUE TITLE
Chunk loading ward uncraftable

### ISSUE THREAD

**Issue by Iplay2L8** [8bit-Build/Peace-of-Mind#10]
Quest for chunk loading ward is unobtainable. requires villager in lasso but villager hearts is set to 0.0/0.0 cant capture a dead villager needs to be changed to 20/20.  or quest needs to be removed and 
 FTB utilities used to load chunks. it has claimed chunks that can be loaded

**Comment by chunkedelement** [comment]
Ok thanks will adjust next update as FTB is mainly used for chunkloading now.

**Comment by chunkedelement** [comment]
FTB chunk-loading Quest will replace

**Comment by chunkedelement** [comment]
Updated for 2.1.1

**Comment by chunkedelement** [comment]
Updated in Pack version 2.1.1
