### ISSUE TITLE
Crashing For No Reason at All (2.1.0)

### ISSUE THREAD

**Issue by coldReactive** [8bit-Build/Peace-of-Mind#13]
Pack Version: 2.1.0
Forge Version: forge-14.23.5.2847
Problem/Issue: Crash during FoamFix Deduplication (As a note, FoamFix is required for me to actually play, otherwise I'd end up freezing every 5-10 seconds even though I have 60 FPS when not freezing.)

Crash Log: https://pastebin.com/ZL9QPZZN

Removing Chunk Animator shouldn't cause crashes. (There's no way to turn off chunk animator animations in-game or via mod options, and the "Disable" button in-game doesn't work. I'm pretty sure the Modpack person or someone else told me to even disable it if I don't like it.) It didn't the last time I played, and played for nearly 8 hours before I tried to play again today. Also, Crashing on FoamFix Deduplication wouldn't be caused by removing Chunk Animator.

**Comment by chunkedelement** [comment]
This is a isolated java runtime issue. Try using a newer version of java build 1.8.0_51 is a bit outdated. Have you tried loading the pack with multimc to verify it’s not a twitch issue? Also chunk animator Mod can be removed if you don’t like it’s optional.

**Comment by coldReactive** [comment]
Using Java 8 Update 261 seems to work for now. However, Minecraft java Windows Launcher won't save the java executable used, and will always revert to the bundled java version (Which is always Update 51.) This happens even on vanilla installs. So I'll have to manually edit the install every time I boot up the modpack.

**Comment by chunkedelement** [comment]
Ok cool see if you can try multimc loader, just download the pack from curse forge and import the instance in multi mc. I ran into this issue on one of my PCs once with another modpack, on the laptop it would load fine but desktop it would crash upon startup due to java runtime error. Twitch has been hit or miss and curse launcher is being redone since the demerger. Does other packs give you this issue?

**Comment by chunkedelement** [comment]
https://multimc.org/

**Comment by coldReactive** [comment]
Do I have to actually go to the files section of the modpack to do this? Or can I just put the modpack curseforge page into multimc instead? Because MultiMC apparently offers URL support for curse: https://github.com/MultiMC/MultiMC5/commit/725ec356350175ba08bca0eae8475dc2654dd10a

**Comment by chunkedelement** [comment]
-Unknown if urls are working 100% with the migration-

-Just download the pack https://www.curseforge.com/minecraft/modpacks/peace-of-mind/download/2906689
-Open multimc
-click on add instance button top left
-click on import from zip
-click browse
-goto downloads folder (or whichever folder you download to) select the Peace+of+Mind-2.1.0.zip file you just downloaded and click open
-click ok
-pack should install in main menu
-click to run pack

**Comment by chunkedelement** [comment]
you can copy your world over and put in-> instance folder, minecraft, saves folder

**Comment by chunkedelement** [comment]
Closing twitch/Java version. Twitch EOL. Use curse, multimc, or updated loader. Thanks
