### ISSUE TITLE
Hell Sprouts In nether overspawn.

### ISSUE THREAD

**Issue by chunkedelement** [8bit-Build/Peace-of-Mind#20]
Peace of Mind: 2.1.1
Forge: 14.23.5.2855
Mystical World:  1.12.2-1.9.2.jar
Mystical Lib: 1.12.2-1.9.0.jar

-Thousands of Hell Sprouts In nether on server and client version 
-Also noticed a lot of lava_cats more than normal on the server
![2021-01-26_21 02 53](https://user-images.githubusercontent.com/34798853/105936442-a9916f00-6021-11eb-9220-a66f7e33651d.png)

Reference issue:
https://github.com/MysticMods/MysticalWorld/issues/226

Have tried: 
-/kill @e[type=mysticalworld:entity_hell_sprout] killed >3000 in the nether
-Tried Setting in the mysticalworld.cfg:

    hellsprout {
        # Biomes to spawn in. List consisting of elements from: |SAVANNA, CONIFEROUS, JUNGLE, SPOOKY, DEAD, LUSH, NETHER, END, MUSHROOM, MAGICAL, RARE, OCEAN, RIVER, WATER, MESA, FOREST, PLAINS, MOUNTAIN, HILLS, SWAMP, SANDY, SNOWY, WASTELAND, BEACH, VOID|
        S:biomes <
            NETHER
         >

        # Maximum number of sprouts to spawn in a group
        I:max=1

        # Min number of sprouts to spawn in a group
        I:min=1

        # Chance (1 in X) for hell sprouts to plant netherwart while on eligible soils
        I:plantChance=90

        # Spawn rate of hell sprouts
        I:rate=2
    }
but still spawning >1000

**Comment by noobanidus** [comment]
I only just noticed this link back to my report. All of the other reports I've received have been for 1.14 or later. This seems to only be happening in modded Nether biomes, which is unfortunate as those are difficult for me to test against in development. 

I believe Visceral Heap is the Biomes o' Plenty modded Nether biome. I'm not sure if they use a custom world generator/chunk generator for the Nether, that possibly may have some impact on it.

The issue in 1.16 appears to be the frequency at which the per-biome weight is inflated for some biomes and not others. Me adjusting manually for this inflation was what I first thought the issue was. Coupled with the fact that, until 1.16, entities registered as `CREATURE` just never spawned in the Nether.

**Comment by chunkedelement** [comment]
Appreciate the update, may just disable these mobs on the server config or see if possible to disable just in certain biomes that are from biomes o plenty related.

**Comment by noobanidus** [comment]
I've got a change in the pipeline that's just waiting on a loot table change and then I'll be releasing a new 1.12 version with an option to configure if they're spawned as creatures or mobs. I think that might fix your issue.

**Comment by chunkedelement** [comment]
Excellent thanks for checking and the feedback on the 1.12 version. Will the spawn config rates still be ok if left on 1 or should that be set back to default?

**Comment by noobanidus** [comment]
Re: config rates, I'm not sure, I haven't been able to reproduce this reliably in a 1.12 dev environment where I can easily examine/adjust values. I believe my loot table woes are over (had to redo it three times) so at best a new release within 24 hours.

**Comment by noobanidus** [comment]
@chunkedelement Apologies, I forgot to let you know when it was released. The most recent version should give you config options for hell sprouts and lava cats that specifies which spawn category they appear in.

Unfortunately, if this doesn't solve the issue, then you may just need to disable it.

I would recommend setting them back to their default spawn rates before testing just to get a handle on things.

**Comment by chunkedelement** [comment]
Thanks @noobanidus for the update, will test on defaults for server and client before next POM pack update 2.1.2. Appreciate the mod feedback again.

**Comment by chunkedelement** [comment]
2.1.2 Fix updated per dev,
