### ISSUE TITLE
Why i cant find zmod ? and what is zmod?

### ISSUE THREAD

**Issue by Virz12** [8bit-Build/Peace-of-Mind#22]
After i play minecraft, there is a text that zmod requires Minecraft 1.13 or above. but i cant find a mod with zmod name

what must i do?

![Minecraft 1 12 2 08_07_2022 12_59_22](https://user-images.githubusercontent.com/108918835/177926736-c6f2fc6b-bec9-419c-9c6c-e1b4a90b067a.png)

**Comment by chunkedelement** [comment]
Need more info to go on, logs? Zmod is a 1.14+ level mod that is not part of the peace of mind 1.12.2 mod pack not sure what this is. What source did you download the pack from Curseforge/overwolf? What modloader/launcher is being used to launch the pack? I would recommend reinstalling the pack via the curse/overwolf launcher to verify.

**Comment by Virz12** [comment]
Yeah so..i think that is my mistake, i download it in Youtube and not check the source. But now its completely playable. 

Thank you for the reply. 👋
